server: 
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/qnsystem?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: 
  mail:
    host: smtp.163.com
    username: smg_song@163.com
    password: smg980528
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  resources:
    static-locations:
      0: file:${headimages.uploaddir}
      1: classpath:static

headimages:
  uploaddir: D://headimages/
