server: 
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/qnsystem?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
