server: 
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/qnsystem?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 972327281@qq.com
    password: pftodqbdruknbffc
    properties:
      mail:
        stmp:
          ssl:
            enable: true    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
